USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS FUSION_POC_ROLE;

CREATE WAREHOUSE IF NOT EXISTS FUSION_POC_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FUSION_POC_DB;
CREATE SCHEMA IF NOT EXISTS FUSION_POC_DB.POC_01_02;

GRANT USAGE ON WAREHOUSE FUSION_POC_WH TO ROLE FUSION_POC_ROLE;
GRANT USAGE ON DATABASE FUSION_POC_DB TO ROLE FUSION_POC_ROLE;
GRANT USAGE ON SCHEMA FUSION_POC_DB.POC_01_02 TO ROLE FUSION_POC_ROLE;
GRANT CREATE TABLE ON SCHEMA FUSION_POC_DB.POC_01_02 TO ROLE FUSION_POC_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA FUSION_POC_DB.POC_01_02 TO ROLE FUSION_POC_ROLE;
GRANT CREATE STAGE ON SCHEMA FUSION_POC_DB.POC_01_02 TO ROLE FUSION_POC_ROLE;
GRANT CREATE GIT REPOSITORY ON SCHEMA FUSION_POC_DB.POC_01_02 TO ROLE FUSION_POC_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE FUSION_POC_ROLE;

-- Optional:
-- GRANT ROLE FUSION_POC_ROLE TO USER <YOUR_USER>;

USE ROLE FUSION_POC_ROLE;
USE WAREHOUSE FUSION_POC_WH;
USE DATABASE FUSION_POC_DB;
USE SCHEMA POC_01_02;
