USE ROLE ACCOUNTADMIN;
USE DATABASE FUSION_POC_DB;
USE SCHEMA POC_01_02;

-- For private GitHub repositories, create a secret:
-- CREATE OR REPLACE SECRET GITHUB_FUSION_BETA_SECRET
--   TYPE = PASSWORD
--   USERNAME = '<github_username>'
--   PASSWORD = '<github_personal_access_token>';

CREATE OR REPLACE API INTEGRATION GITHUB_FUSION_BETA_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/barauna-lo')
  ENABLED = TRUE
  -- For private repositories, uncomment:
  -- ALLOWED_AUTHENTICATION_SECRETS = (GITHUB_FUSION_BETA_SECRET)
;

GRANT USAGE ON INTEGRATION GITHUB_FUSION_BETA_API_INTEGRATION TO ROLE FUSION_POC_ROLE;

USE ROLE FUSION_POC_ROLE;
USE WAREHOUSE FUSION_POC_WH;
USE DATABASE FUSION_POC_DB;
USE SCHEMA POC_01_02;

CREATE OR REPLACE GIT REPOSITORY FUSION_BETA_REPO
  API_INTEGRATION = GITHUB_FUSION_BETA_API_INTEGRATION
  ORIGIN = 'https://github.com/barauna-lo/fusion_beta.git'
  -- For private repositories, uncomment:
  -- GIT_CREDENTIALS = GITHUB_FUSION_BETA_SECRET
;

ALTER GIT REPOSITORY FUSION_BETA_REPO FETCH;

LIST @FUSION_BETA_REPO/branches/main;
