USE ROLE FUSION_POC_ROLE;
USE WAREHOUSE FUSION_POC_WH;
USE DATABASE FUSION_POC_DB;
USE SCHEMA POC_01_02;

ALTER GIT REPOSITORY FUSION_BETA_REPO FETCH;

CALL POC_01_02_RUN_EXPERIMENT(
    'poc_01_02_manual_test_001',
    2042,
    42
);

SELECT *
FROM POC_01_02_TURBULENCE_SERIES
WHERE RUN_ID = 'poc_01_02_manual_test_001'
ORDER BY STEP
LIMIT 10;

SELECT RUN_ID, METADATA_JSON, CREATED_AT
FROM POC_01_02_ENVIRONMENT
WHERE RUN_ID = 'poc_01_02_manual_test_001';

SELECT RUN_ID, ARTIFACT_NAME, ARTIFACT_TYPE, STORAGE_BACKEND, STORAGE_REFERENCE, CREATED_AT
FROM POC_01_02_ARTIFACT_MANIFEST
WHERE RUN_ID = 'poc_01_02_manual_test_001'
ORDER BY CREATED_AT;

SELECT CONTENT_TEXT
FROM POC_01_02_ARTIFACT_MANIFEST
WHERE RUN_ID = 'poc_01_02_manual_test_001'
  AND ARTIFACT_NAME = 'turbulence_dashboard.html';
